version: '3.8'

services:

  sudoku-frontend:
    container_name: sudoku-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8888:3000
    environment:
      - CHOKIDAR_USEPOLLING=true